# -*- coding: utf-8 -*-
"""ECT_HW1_1044033553_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NtBjxz0ExVNDYh-4fvpi2UO22wG4iaxl
"""

import pandas as pd
#讀取CSV檔案
data = pd.read_csv('diabetes.csv')

data.info()

data.describe()

#x:input
x=data.loc[:,['preg','plas','pres','skin','insu','mass','pedi','age']]
#y:output
y=data.loc[:,['class']]

from sklearn import preprocessing

le = preprocessing.LabelEncoder()


#將play轉為數字label
#play: no: 0 ,yes: 1
Y_class_label=le.fit_transform(y['class'])

#將屬性合併
#變成list
feature=list(zip(x.preg,x.plas,x.pres,x.skin,x.insu,x.mass,x.pedi,x.age))

#轉成array
import numpy as np
features=np.asarray(feature)

#Import Gaussian Naive Bayes 模型 (高斯樸素貝氏)
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

# 訓練集訓練模型
# model.fit(x, y)
model.fit(features, Y_class_label)

expected = Y_class_label
predicted = model.predict(features)
from sklearn import metrics
print(metrics.classification_report(expected, predicted))

print(metrics.confusion_matrix(expected, predicted))

predicted= model.predict([[2,1,0,0,2,1,2,20]]) 
print ("Predicted Value:", predicted)

